### PR TITLE
Elo tournament system using Challonge api.

### PR DESCRIPTION
**Pull request by Chen-ygopro**

### CODE REVIEW

**Comment by IrateGod** [comment]
Hey @Chen-ygopro, appreciate the effort you put into this PR, but right now this looks very raw and there is no integration into our current system yet. Do you plan on writing those still?

**Comment by Chen-ygopro** [comment]
Sorry not very good english still learning

**Comment by Chen-ygopro** [comment]
Your softwear allows full embed right?

**Comment by Zayelion** [comment]
Ok I'm going to fail this pull request for the moment here is the reasoning.

- The server is running an older version of node and doesnt work with const
- The configuration settings of those working on the project arent set up for es6 yet
- The launcher uses isomophic code in many places and so the whole server is written in es5 not es6
- We use callbacks not promises as a rule
- We and the greater community leaders decided AGAINST using Elo as the ranking system.
- We have a point based ranking system that we wish to automate.
- You included your node_modules folder which will kill all our machines and make it so none of the developers can pull this repo out of Github again. Delete it... its in .gitignore for a reason.

For more information read the documentation files in the documentation folder.

**Comment by Zayelion** [comment]
Refer to this : https://github.com/SalvationDevelopment/YGOPro-Salvation-Server/blob/master/libs/database.js

**Comment by Chen-ygopro** [comment]
What;s your formula?

**Comment by Chen-ygopro** [comment]
I'll rework this on the weekend because i will be busy all week.

**Comment by Chen-ygopro** [comment]
How do i set up a test environment?

**Comment by Chen-ygopro** [comment]
If my understanding is correct salvation want's their own bracket system? In addition to automation of the point ranking system used by the server? Also is the bracket system only for official tourneys and do you guys count unofficial( ie not hosted by staff) ones for ranking?

**Comment by Zayelion** [comment]
> If my understanding is correct salvation want's their own bracket system,in addition to automation of the point ranking system used by the server? Also is the bracket system only for official tourneys and do you guys count unofficial( ie not hosted by staff) ones for ranking?

Yes we do want our own bracketing system. We are testing that the point system reflects users skill properly at the moment and tweeking our formulas on what is reported and how things are calculated.

Only admins will have access to the tournament controls. They are designed in a way to make it more fluid for duelist to join tournaments; reduction of steps. That said, our current policy is that if anyone host a tournament if it was a fair tournament its added to the rankings after review.

Ideally after we gain a large number of users tournaments would start every hour, or on completion of a large one.

Read over `libs/gamelist` and `http/js/http-gamelist.js` for an understanding of how the launcher interacts with the server.

**Comment by Chen-ygopro** [comment]
[http://i.imgur.com/xif8RGC.png](url)
I can not get the server to start. @Zayelion

**Comment by Zayelion** [comment]
Contact me on Discord and I will explain how to get it to work.

**Comment by Chen-ygopro** [comment]
#https://github.com/YGOPro-International/YGOPro-Salvation-Server/commit/b0406945985f88f74d988e704692f3ee52e22bf6

**Pull request closed without merging**
